server {
    listen 80;
    server_name _;

    # 1. Backend API
    location /deploy-config/8200/api/ {
        # Backend runs on port 4050
        proxy_pass http://backend:4050/api/;
    }

    # Handle trailing slash
    location = /deploy-config/8200 {
        return 301 /deploy-config/8200/;
    }

    # 2. Frontend Page
    location /deploy-config/8200/ {
        proxy_pass http://frontend:4000/;
    }

    # 3. Redirect root
    location = / {
        return 302 /deploy-config/8200/;
    }
}
